## How do Drink Preferences Vary in Everyday Life?

Gavin Kelly

### Background

Alcohol Use Disorder is a significant burden to society, and patients often struggle to curtail use outside of clinical settings. Using Ecological Momentary Assessment (EMA) to understand daily patterns of drinking allows us to understand the social, emotional, and physical context in which drinking behavior occurs. However, EMA alcohol use studies typically reduce drinking behavior to simple quantity measures. This approach overlooks the nuanced decision making process behind _what_ people choose to drink and _when_. To address this gap, we explored preference patterns between types of alcoholic and non-alcoholic drinks in real-world contexts.

Intuition and anecdotes suggest preferences vary (e.g. wine at dinner vs beer at a bar), but we lack systematic data on these patterns. Data on drink preferences is difficult to collect; they aren’t completely captured by drinking behavior. Choices for drinks are constrained by context and may reflect availability rather than actual preferences. Understanding preference patterns could reveal how context shapes decisions to drink beyond typical “drink/don’t drink” EMA measures. 

We used an experimental choice task to comprehensively measure participants’ real-time preferences. During each EMA assessment, 250 participants completed 160 choices between alcoholic and non-alcoholic drinks, resulting in 951,028 total choices. Our unique dataset combines real-time choices with rich contextual data. This allows for unprecedented examination of drink-specific preferences in diverse natural contexts. Our use of hypothetical choices for alcohol allows us to examine participants' preferences for alcohol independently from its availability. Furthermore, we present participants with diverse choices for alcoholic and non-alcoholic drinks across a range of baseline preference levels. This allows us to determine which types of drinks participants prefer, and which contexts may lead them to reverse their baseline preferences.

We present extensive descriptive statistics, data visualizations, and statistical analyses to explore these patterns in the data. Our data may indicate whether different drinks serve different functions (e.g. social lubrication, stress relief, celebration), which is unexplored in the literature. We can also determine which non-alcoholic alternatives may curtail drinking and when. This benchmark information indicates future research directions on the patterns and functions of different types of drinks. Furthermore, an understanding of real-time preferences may help adapt interventions to people and contexts.

### Variables of Interest

**subject:** Each of the 250 participants were assigned their own subject ID, 1-250.

**session:** Each time a participant completed an EMA survey, including the 160 trial choice task, this was recorded as one session.

**trial:** Each of the 160 choices participants made during a choice task was recorded as one trial, numbered 1-160 for each session.

**alc_image:** This describes the alcoholic drink option that was offered to the participants for each trial, displayed as a standardized image.

**soft_image:** This describes the non-alcoholic drink option that was offered to the participants for each trial, displayed as a standardized image. In the dataset, non-alcoholic drinks are referred to as soft drinks, even though there are options other than soft drinks.

**response:** Whether participants chose the alcoholic or non-alcoholic (soft) drink option for each trial.

**prop_alc_responses:** This describes the proportion of trials in a session that participants chose the alcoholic option.

**value_function:** For a given trial, the value_function variable describes the participants baseline preferences towards the alcoholic or non-alcoholic drink. During the baseline session, participants rated all the alcoholic and non-alcoholic drink options they would be presented with on a 1-4 scale. For a given trial, which offers a choice between a non-alcoholic and an alcoholic drink, the value_function variable subtracts the non-alcoholic rating from the alcoholic rating. A value_function value of 3 indicates a strong baseline preference towards the alcoholic drink, a value of 0 indicates baseline indifference between the drinks, and a value of -3 indicates strong preference towards the non-alcoholic drink.

**location:** For each session, participants reported the type of location they were in by selecting from a dropdown menu of 7 choices.

**social_context_overall:** For each session, participants described the people they were around by selecting from a dropdown menu of 8 choices.

**time:** For each session, the time of day that participants completed the survey was recorded.

**day_of_week:** For each session, the day of the week that participants completed the survey was recorded.

### Descriptive Figures

#### Figure 1: Alcoholic and Non-Alcoholic Drink Types and Baseline Rating Distributions

<img src="Figures/faceted_drink_plot.jpeg" width="1000">

#### Figure 2: Example Choice Task Trial

<img src="Figures/Drink_Example_Photo.jpeg" width="650">

An example of a single choice made by participants in the choice task. Value function values were not actually displayed during the choice task, they are only included in this figure for context.

#### Figure 3: Overall Choices for Alcohol at Each Level of the Value Function

<img src="Figures/figure7 copy.jpg" width="650">

Participants chose alcohol most frequently when the value function was +3, meaning they had a baseline preference of 4 for the alcoholic option, and 1 for the non-alcoholic option. Participants chose alcohol less than 50% of the time when the value function was 0, meaning they were indifferent at baseline between the alcoholic and non-alcoholic options. Participants chose alcohol least frequently when the value function was -3.

### Hypotheses

We hypothesize that the location, social context, time of day, and day of week that participants completed the choice task will have a statistically significant effect on their choices for alcohol.

Furthermore, we hypothesize that the different choice contexts will exhibit significant interactions with the type of drinks participants are offered when predicting choices for alcohol.

Finally, we will conduct exploratory analyses to determine the grouping of alcoholic and non-alcoholic drinks that most accurately reflects participants' preferences in everyday life.

### Data Organization

#### Data Cleansing

The original dataset was stored in three .csv files. 

Baseline Data: All raw data collected in the baseline session of the study was included in this 250 row .csv file. This includes the baseline drink ratings by all 250 participants, as well as demographic and psychological measures that are not relevant to the current project. In all steps of data cleansing, variables were renamed according to a standard procedure, data was checked for anomalies and missing rows were dropped. All participants had valid baseline data, so no rows were dropped.

Survey Data: One .csv contained the survey data, with one row for each session completed. This file had over 6000 rows.  Variables such as location and social context were combined for convenience. After data cleansing, this file contained 5982 rows of data. 

Choice Task Data: The other .csv file contained the choice task data, without the information about the time, location, social context, etc. when each session was completed. Before data cleansing, this file contained over 1,000,000 rows of choices between alcohol and non-alcoholic drinks. After data cleansing, this file contained 956080 rows of data.

After cleansing all three .csv files, I merged the files so that the data for each participant was combined, and everything was stored in one .csv file.

Data Processing .Rmd scripts are included in the Supplementary Materials.

#### Data Architecture

The data have a double-nested structure, with EMA sessions nested in participants, and choice task trials nested within each session. Each participant completed an average of 23.91 sessions. The average number of trials completed per session was 159.12, meaning participants completed all 160 trials in almost every session.

After removing irrelevant variables, the data for each participant includes measures from both baseline and EMA assessments. This means that certain observations are repeated across sessions and trials. We standardized all measures and converted relevant variables to factors to create our final tidy-compliant dataset, which can be referenced in the Supplemental Materials section.

#### Resulting Tidy-Compliant Table

In [3]:
tidy_data = read.csv(file="Supplementary_Materials/DSPN_tidy_data.csv")
head(tidy_data)

  subject session trial prop_alc_responses day_of_week social_context_overall
1 1       1       1     0.7625             Fri         alone
2 1       1       2     0.7625             Fri         alone
3 1       1       3     0.7625             Fri         alone
4 1       1       4     0.7625             Fri         alone
5 1       1       5     0.7625             Fri         alone
6 1       1       6     0.7625             Fri         alone
  location    time     value_function response alc_image soft_image
1 school_work 16:23:59  2             alc      alc02.jpg soft16.jpg
2 school_work 16:23:59  3             alc      alc02.jpg soft13.jpg
3 school_work 16:23:59  1             alc      alc07.jpg soft02.jpg
4 school_work 16:23:59  1             alc      alc25.jpg soft10.jpg
5 school_work 16:23:59 -3             soft     alc11.jpg soft09.jpg
6 school_work 16:23:59 -2             soft     alc30.jpg soft18.jpg

## Data Analysis

### Technique #1: Linear Mixed-Effects Models

Before examining specific drink types, we will investigate whether participants' choices for alcohol differ across different contexts. The contexts we will be testing are location, social context, time of day, and day of week. Because the data is nested, we can't run a simple Anova to test whether choices differ by location, for example. Since the data for each session are not independent, but nested within each participant, we will run Linear Mixed-Effects Models to test each contextual variable.

We used a random intercept model to control for participants' baseline differences in preferences for alcohol. Our dataset could not support random slopes as well, because including a random slope for every location type for every participant requires too much computational power. However, our hypothesis assumes trends across participants in different locations are uniform, so using random intercepts is appropriate.

We only display the output of our first model, in which we use location to predict choices for alcohol, below. We use the same approach for all four models, so we will summarize each in turn. Our data is accessible in the Supplemental Materials section.

#### Location Mixed-Effects Model

In [25]:
ema_lead <- read.csv(file="Supplementary_Materials/ema_lead.csv") # Load data on the session level
suppressPackageStartupMessages({
library(lmerTest)
library(lme4)
    })
ema_lead$location <- relevel(factor(ema_lead$location), ref = "home")
model_location <- lmer(prop_alc_responses ~ location + (1 | subject), data = ema_lead)
summary(model_location)

Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: prop_alc_responses ~ location + (1 | subject)
   Data: ema_lead

REML criterion at convergence: -3030.5

Scaled residuals:
    Min      1Q  Median      3Q     Max
-3.8822 -0.4870 -0.0365  0.4289  4.6885

Random effects:
 Groups   Name        Variance Std.Dev.
 subject  (Intercept) 0.03960  0.1990
 Residual             0.03033  0.1742
Number of obs: 5951, groups:  subject, 247

Fixed effects:
                             Estimate Std. Error         df t value Pr(>|t|)
(Intercept)                 3.598e-01  1.298e-02  2.530e+02  27.715  < 2e-16
locationbar_club            1.459e-01  2.770e-02  5.729e+03   5.267 1.44e-07
locationother               9.757e-03  1.126e-02  5.776e+03   0.866    0.386
locationoutdoors           -6.650e-03  1.299e-02  5.757e+03  -0.512    0.609
locationrestaurant_cafe     1.054e-01  2.260e-02  5.727e+03   4.664 3.17e-06
locationschool_work        -6.783e-02  9.104e-03  5.781e+03  -7.450 1.07e-13
locationsomeone_elses_home  5.670e-02  1.418e-02  5.757e+03   3.997 6.49e-05

(Intercept)                ***
locationbar_club           ***
locationother
locationoutdoors
locationrestaurant_cafe    ***
locationschool_work        ***
locationsomeone_elses_home ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Correlation of Fixed Effects:
            (Intr) lctnb_ lctnth lctntd lctnr_ lctns_
loctnbr_clb -0.023
locationthr -0.060  0.046
locatintdrs -0.050  0.029  0.078
lctnrstrnt_ -0.027  0.030  0.054  0.049
lctnschl_wr -0.071  0.043  0.088  0.078  0.058
lctnsmn_ls_ -0.046  0.043  0.070  0.065  0.047  0.073

#### Social Context Mixed-Effects Model

In [24]:
# Make alone the baseline, as this is the social context with the most observations
ema_lead$social_context_overall <- relevel(factor(ema_lead$social_context_overall), ref = "alone")
model_social <- lmer(prop_alc_responses ~ social_context_overall + (1 | subject), data = ema_lead)
anova(model_social)

                       Sum Sq   Mean Sq   NumDF DenDF    F value  Pr(>F)
social_context_overall 3.601576 0.5145108 7     5802.705 16.92276 2.772117e-22

#### Time of Day Mixed-Effects Model

In [23]:
model_time <- lmer(prop_alc_responses ~ time_of_day + (1 | subject), data = ema_lead)
anova(model_time)

            Sum Sq   Mean Sq  NumDF DenDF    F value  Pr(>F)
time_of_day 5.629173 5.629173 1     5724.509 187.4815 5.146419e-42

#### Day of Week Mixed-Effects Model

In [22]:
model_day <- lmer(prop_alc_responses ~ day_of_week + (1 | subject), data = ema_lead)
anova(model_day)

            Sum Sq   Mean Sq   NumDF DenDF    F value  Pr(>F)
day_of_week 1.604603 0.2674339 6     5706.432 8.697115 1.896394e-09

All four contexts significantly predict participants' proportion of choices for alcohol when controlling for participants' baseline preferences. Our hypothesis was confirmed; context predicts alcohol preferences with statistical significance across all participants in our sample.

Now we will investigate whether preferences for a certain type of drink drive these contextual preferences. Our Mixed-Effects Model showed us that preferences are higher in bar/club and restaurant/cafe settings when compared to home. Intuition tells us that increased preferences for liquor might cause increased preferences for alcohol in a bar/club, and people in a restaurant/cafe might only have increased preferences for wine. We will investigate whether these intuitions hold, and preferences for a certain drink type are significantly associated with changing preferences for alcohol in different contexts.

We first present descriptive data visualizations to cultivate a better understanding of the data structure, with a specific focus on the alcoholic drink types, and to set the stage for our statistical analyses.

### Visualizing Alcoholic Drink Types

<img src="Figures/n_obs_plot.jpeg" width="650">

Here, we plot the total number of trials that included a given type of alcoholic drink by the value function. These counts are directly related to the size of the drink groups. Many of the alcoholic drink options we presented to participants were classified as liquor, and because this was the most common drink type, it appeared in more trials. 

The counts are also related to the baseline ratings of participants. Observe how beer has a right-skewed distribution, while wine has a left-skewed distribution. This is because baseline ratings of beer were lower than wine. Therefore, it was more likely that participants were offered a choice where they preferred a non-alcoholic drink over beer (compared to seltzer), and vice versa.

Importantly, for a given 160-trial choice task, we ensured that participants had no baseline bias towards alcoholic versus non-alcoholic drinks. This means that, for a given choice task session, the number of choices for which they preferred alcohol (at baseline) was equal to the number of choices they preferred the non-alcoholic option. This took the weights into account, so the value function values for one session would sum to zero. This also means that there are the same number of observations to the left of 0 as to the right of 0 in the above plot.

<img src="Figures/drinks_value_plot.jpeg" width="1000">

Here, similarly to Figure 3, we can observe the differences in choices between different drink types at each level of the value function. There appears to be overall preferences for Seltzer and Soda, and preferences appear to be consistent across most levels of the value function. Of note, there appears to be a slight a floor effect for preferences of alcohol when participants hold a strong preference for the non-alcoholic option (at value -3). Also, participants preferences for non-alcoholic drink types appear to converge when participants hold a slight preference for the alcoholic option (value 1 and 2). However, nothing can be concluded from these observations without performing statistical testing.

<img src="Figures/DSPN_figure1.jpg" width="1000">

In this plot we observe the means and jittered distributions for choices for alcoholic drink types across different contexts. Using a simple eyeball test, the patterns between different drink types appear to remain constant across different contexts. For example, no matter the day of the week, seltzer has the highest proportion of choices, and liquor has the lowest. 

To investigate whether a significant difference exists in preferences for drink types across different contexts, we will run re-run our Linear Mixed-Effects Models with drink type as an interaction term.

### Linear Mixed-Effects Models with Interaction Terms

In [30]:
# load data in long format, with a column that includes proportions for all drink types
ema_long = read.csv(file="Supplementary_Materials/ema_long.csv")

#### Location * Drink Type

In [32]:
model_loc_drink <- lmer(prop_drink_type_responses ~ location * drink_type + (1 | subject), 
                        data = ema_long)
anova(model_loc_drink)

                    Sum Sq    Mean Sq   NumDF DenDF    F value   Pr(>F)
location            15.502774 2.5837956  6    23634.42 39.867438 1.484379e-48
drink_type           9.445984 3.1486615  3    23528.25 48.583203 2.715598e-31
location:drink_type  2.921732 0.1623185 18    23528.25  2.504541 4.070498e-04

Here we see a significant interaction effect, meaning preference patterns for drink types change based on location. We can visualize the output of the model using the "emmeans" package for ease of interpretation:

<img src="Figures/model_loc_drink_plot.jpeg" width="750">

When analyzing this interaction, we must pay attention to how the patterns of drink type preferences change between locations. If the lines are semi-parallel, then the relative preferences are staying constant. For example, preferences for seltzer are predicted to be significantly higher than liquor in every location. 

On the other hand, crossing lines indicate changes in preference patterns. For example preferences for beer and wine are not significantly different than liquor except at home or another's home. This indicates that beer and wine help people relax in calm environments, while liquor does not serve the same purpose.

Furthermore, the only contexts in which seltzer is not significantly preferred over either beer or wine is in a Bar/Club or at a Restaurant. This indicates that these locations smooth preferences. Customers simply want to drink alcohol, and aren't picky about the kind. This is also reflected by the higher overall level of choices for alcohol in these locations.

#### Social Context * Drink Type

In [33]:
model_soc_drink <- lmer(prop_drink_type_responses ~ social_context_overall * drink_type + (1 | subject), data = ema_long)
anova(model_soc_drink)

                                  Sum Sq   Mean Sq   NumDF DenDF    F value
social_context_overall            12.48373 1.7833895  7    23708.21 27.51391
drink_type                        16.26082 5.4202744  3    23524.30 83.62330
social_context_overall:drink_type  6.12638 0.2917324 21    23524.30  4.50081
                                  Pr(>F)
social_context_overall            6.125325e-38
drink_type                        8.199914e-54
social_context_overall:drink_type 2.820182e-11

We observe a significant interaction effect, so we visualize the interaction below:

<img src="Figures/model_soc_drink_plot.jpeg" width="750">

Again, across different social contexts, seltzer is consistently preferred over liquor. However, there are some interactions involving beer and wine. When participants were around multiple types of people or strangers, they preferred beer, wine, and liquor equally. This might indicate that in unfamiliar or uncomfortable situations, seltzer is significantly preferred to other types of drinks. Of note, overall preferences are not significantly different in these contexts, but seltzer might be the drink that participants identify as the best "social lubricant."

On the other hand, when participants were alone or with family, beer and wine were significantly preferred over liquor. Also, when participants were with their romantic partner, they significantly preferred wine over liquor. This might again indicate that beer and wine are more preferred in relaxed contexts with familiar people than liquor.

#### Time of Day * Drink Type

Before running the interaction with Time of Day, we filter out the hours for which we have too few observations, and convert the variable to a factor.

In [36]:
suppressPackageStartupMessages ({ library(dplyr) })
ema_long_filtered <- ema_long %>%
  filter(hour >= 15 & hour <= 22) %>%
  mutate(hour_factor = factor(paste0(hour, ":00"), 
                              levels = paste0(15:22, ":00"), 
                              ordered = TRUE))

In [37]:
model_time_drink <- lmer(prop_drink_type_responses ~ hour_factor * drink_type + (1 | subject), 
                        data = ema_long_filtered)
anova(model_time_drink)

                       Sum Sq   Mean Sq    NumDF DenDF    F value
hour_factor            25.10566 3.58652262  7    22541.47  55.514958
drink_type             25.58763 8.52920942  3    22461.70 132.021668
hour_factor:drink_type  1.70278 0.08108475 21    22461.70   1.255092
                       Pr(>F)
hour_factor            3.322813e-79
drink_type             8.773399e-85
hour_factor:drink_type 1.933214e-01

We see that the interaction term is not significant, so we won't explore this model further.

#### Day of Week * Drink Type

In [38]:
model_day_drink <- lmer(prop_drink_type_responses ~ day_of_week * drink_type + (1 | subject), 
                        data = ema_long)
anova(model_day_drink)

                       Sum Sq     Mean Sq     NumDF DenDF    F value
day_of_week             5.8222306  0.97037177  6    23543.02  14.8522767
drink_type             55.2546511 18.41821703  3    23528.23 281.9047943
day_of_week:drink_type  0.3413402  0.01896334 18    23528.23   0.2902484
                       Pr(>F)
day_of_week             4.998720e-17
drink_type             8.657016e-180
day_of_week:drink_type  9.984630e-01

We see here that the interaction term is not significant, so we won't explore this model further.

In summary, we observed significant interactions between drink type and location, and drink type and social context. It appears if our goal is to identify the contexts in which drink types are important, location and social context are the most relevant. We identified that seltzer is significantly preferred over liquor across contexts. Also, beer and wine appear to be preferred in more comfortable or relaxed contexts, while they are comparable to liquor in more unfamiliar or uncomfortable contexts. In these contexts, seltzer may be viewed as best "social lubricant." While these patterns are interesting, they are only based on observational data, and offer exciting future directions for future experimental research and potential interventions.

We are also interested in how non-alcoholic drinks play into these interactions. Now that we have developed an understanding of the patterns in which preferences for drink types change, it would be valuable to understand which non-alcoholic drinks might be valuable substitutes for different alcoholic drinks. Then, in high-risk contexts, relevant substitutes for alcohol can be made readily available.

### Technique #2: Correlation Matrix

To identify which non-alcoholic drinks might act as substitutes for different alcoholic drink types, we can use a correlation matrix to identify the pairs for which preferences overlap.

In [ ]:
Technique #2 Code

### Technique #3: Reclassifying drinks

In [ ]:
technique #3 code

Conclusions

#### Supplementary Materials

Detailed data cleansing, visualization, and analysis .Rmd scripts can be found in the [Supplementary Materials folder](./Supplementary_Materials).